name: Process request issue

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  process-request-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js version from .nvmrc
        id: set-node
        run: echo "::set-output name=node::$(cat .nvmrc)"

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.set-node.outputs.node }}

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install NPM dependencies
        run: npm ci

      - name: Process the issue
        run: >-
          node src/cli.js github issue-request
          --token=${{ secrets.GITHUB_TOKEN }}
          --repository=${{ github.event.repository.full_name }}
          --number=${{ github.event.issue.number }}
